version: '3'
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres_password
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
    command: ["node", "index.js"]
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379